global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: aggregator
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - localhost:3000
